In [54]:
#import packages
import numpy as np 
import pandas as pd 
from sklearn.ensemble import RandomForestClassifier
np.random.seed(1234)
from sklearn import preprocessing
from sklearn import utils

In [121]:
#import training data
training = pd.read_csv('newtrain.csv', encoding = 'utf-8')

In [103]:
training.head()

,user_id,region,city,parent_category_name,category_name,title,description,price,item_seq_number,user_type,image_top_1,deal_probability,Weekday,Weekd of Year,Day of Month,text_feat,description_num_chars,description_num_words,description_num_unique_words,description_words_vs_unique,text_feat_num_chars,text_feat_num_words,text_feat_num_unique_words,text_feat_words_vs_unique,title_num_chars,title_num_words,title_num_unique_words,title_words_vs_unique
0,675853,19,460,4,42,кокоби(кокон для сна),"кокон для сна малыша,пользовались меньше месяц...",5.991467,2,1,13,0.12789,1,13,28,постельные принадлежности nan nan,58,7,7,100.0,33,4,3,75.000000,21,3,3,100.0
1,173962,17,1300,2,22,стойка для одежды,"стойка для одежды, под вешалки. с бутика.",8.006368,19,1,2722,0.00000,6,12,26,другое nan nan,41,7,7,100.0,14,3,2,66.666667,17,3,3,100.0
2,440069,16,1276,0,2,philips bluray,"в хорошем состоянии, домашний кинотеатр с blu ...",8.294050,9,1,2260,0.43177,0,12,20,"видео, dvd и blu-ray плееры nan nan",99,17,17,100.0,35,7,6,85.714286,14,2,2,100.0
3,576929,21,940,4,42,автокресло,продам кресло от0-25кг,7.696213,286,0,2837,0.80323,5,12,25,автомобильные кресла nan nan,22,3,3,100.0,28,4,3,75.000000,10,1,1,100.0
4,721853,4,317,6,0,"ваз 2110, 2003",все вопросы по телефону.,10.596635,3,1,1408,0.20797,3,11,16,с пробегом ваз (lada) 2110,24,4,4,100.0,26,5,5,100.000000,14,3,3,100.0

In [107]:
#drop columns that will not be used (text columns) 
training=training.drop(['title', 'description', 'text_feat'], axis=1)
training.head()

,Weekd of Year,Day of Month,description_num_chars,description_num_words,description_num_unique_words,description_words_vs_unique,text_feat_num_chars,text_feat_num_words,text_feat_num_unique_words,text_feat_words_vs_unique,title_num_chars,title_num_words,title_num_unique_words,title_words_vs_unique,user_id,region,city,parent_category_name,category_name,price,item_seq_number,user_type,image_top_1,deal_probability
0,13,28,58,7,7,100.0,33,4,3,75.000000,21,3,3,100.0,675853,19,460,4,42,5.991467,2,1,13,0.12789
1,12,26,41,7,7,100.0,14,3,2,66.666667,17,3,3,100.0,173962,17,1300,2,22,8.006368,19,1,2722,0.00000
2,12,20,99,17,17,100.0,35,7,6,85.714286,14,2,2,100.0,440069,16,1276,0,2,8.294050,9,1,2260,0.43177
3,12,25,22,3,3,100.0,28,4,3,75.000000,10,1,1,100.0,576929,21,940,4,42,7.696213,286,0,2837,0.80323
4,11,16,24,4,4,100.0,26,5,5,100.000000,14,3,3,100.0,721853,4,317,6,0,10.596635,3,1,1408,0.20797

In [122]:
#split "training" dataset into train and test sets
training['is_train'] = np.random.uniform(0, 1, len(training)) <= .75
train, test = training[training['is_train']==True], training[training['is_train']==False]

In [124]:
#train random forest classifier
clf = RandomForestClassifier(n_jobs=2, random_state=0)
features = (['Weekday', 'Weekd of Year', 'Day of Month', 'description_num_chars',
       'description_num_words', 'description_num_unique_words',
       'description_words_vs_unique', 'text_feat_num_chars',
       'text_feat_num_words', 'text_feat_num_unique_words',
       'text_feat_words_vs_unique', 'title_num_chars', 'title_num_words',
       'title_num_unique_words', 'title_words_vs_unique', 'user_id', 'region',
       'city', 'parent_category_name', 'category_name', 'price',
       'item_seq_number', 'user_type', 'image_top_1'])

y = train['deal_probability']
y=y.astype('int')

clf.fit(train[features], y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=2, oob_score=False, random_state=0,
            verbose=0, warm_start=False)

In [115]:
features

Index(['Weekd of Year', 'Day of Month', 'description_num_chars',
       'description_num_words', 'description_num_unique_words',
       'description_words_vs_unique', 'text_feat_num_chars',
       'text_feat_num_words', 'text_feat_num_unique_words',
       'text_feat_words_vs_unique', 'title_num_chars', 'title_num_words',
       'title_num_unique_words', 'title_words_vs_unique', 'user_id', 'region',
       'city', 'parent_category_name', 'category_name', 'price',
       'item_seq_number', 'user_type', 'image_top_1'],
      dtype='object')

In [125]:
#test classifier on test data (subset of training data)
pred = clf.predict(test[features])

In [126]:
#calculate RMSE
#define RMSE
def rmse(predictions, targets):
    return np.sqrt(((predictions - targets) ** 2).mean())
#apply RMSE function
rmse(pred, test['deal_probability'])

0.29473651254907196

In [127]:
list(zip(train[features], clf.feature_importances_))

[('Weekday', 0.029748405826792113),
 ('Weekd of Year', 0.013452384188374697),
 ('Day of Month', 0.040193812933325246),
 ('description_num_chars', 0.070018158003836942),
 ('description_num_words', 0.051055708087219064),
 ('description_num_unique_words', 0.051047450607180619),
 ('description_words_vs_unique', 0.042223816096120782),
 ('text_feat_num_chars', 0.06708038634593802),
 ('text_feat_num_words', 0.01547465913676512),
 ('text_feat_num_unique_words', 0.020078267996682369),
 ('text_feat_words_vs_unique', 0.013956696477135244),
 ('title_num_chars', 0.057806848817802278),
 ('title_num_words', 0.025517770372637843),
 ('title_num_unique_words', 0.02430492955710992),
 ('title_words_vs_unique', 0.0017367411714544569),
 ('user_id', 0.074256890313769849),
 ('region', 0.052043496648944976),
 ('city', 0.064515901148471028),
 ('parent_category_name', 0.05213609262329786),
 ('category_name', 0.037909619607486546),
 ('price', 0.057041491725863404),
 ('item_seq_number', 0.054771398361327793),
 ('user_type', 0.0087934942631352434),
 ('image_top_1', 0.074835579689328607)]

In [128]:
#apply predictions to testing data for kaggle contest

#load and preparetesting data
testing = pd.read_csv('newtest.csv', encoding = 'utf-8') 
testing = testing.drop(['title', 'description', 'text_feat'], axis=1)

#create predictions for testing data
testing['rf_test_pred'] = clf.predict(testing[features])
testing['deal_probability'] = testing['rf_test_pred']

In [3]:
import pandas as pd
testing = pd.read_csv('newtest.csv', encoding = 'utf-8')